[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
evm_version = "cancun"
auto_detect_solc = true
optimizer = true
optimizer_runs = 10_000
additional_compiler_profiles = [ { name = "via-ir", via_ir = true } ]
compilation_restrictions = [
  { paths = "./src/interfaces/IPancakeSwapV4StandardModule.sol", via_ir = true },
  { paths = "./src/interfaces/IPancakeSwapV4StandardModuleResolver.sol", via_ir = true },
  { paths = "./src/abstracts/PancakeSwapV4StandardModule.sol", via_ir = true },
  { paths = "./src/modules/PancakeSwapV4StandardModulePrivate.sol", via_ir = true },
  { paths = "./test/integration/PancakeSwapV4Integration.t.sol", via_ir = true },
  { paths = "./test/integration/UniV4Integration.t.sol", via_ir = true },
  { paths = "./test/unit_tests/PancakeSwapV4StandardModule/PancakeSwapV4StandardModule.t.sol", via_ir = true },
  { paths = "./test/unit_tests/PancakeSwapV4StandardModulePrivate/PancakeSwapV4StandardModulePrivate.t.sol", via_ir = true },
  { paths = "./test/unit_tests/UniV4StandardModule/UniV4StandardModule.t.sol", via_ir = true },
  { paths = "./test/unit_tests/UniV4StandardModulePrivate/UniV4StandardModulePrivate.t.sol", via_ir = true },
  { paths = "./script/setHookPoolKey.s.sol", via_ir = true },
 # Add more as needed
]

[profile.lite]
optimizer = false
optimizer_runs = 0
extra_output_files = []
dynamic_test_link = true

[fmt]
line_length = 70
multiline_func_header = "params_first"
number_underscore = "thousands"
