[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
cancun = true
solc_version = "0.8.22"
[fmt]
line_length = 70
multiline_func_header = "params_first"
number_underscore = "thousands"